# Generated by Django 6.0 on 2025-12-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('rok_produkcji', models.IntegerField(verbose_name='Rok produkcji')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Numer VIN')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samochody', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
