# Generated by Django 6.0 on 2025-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzaj', '0002_wizyta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizyta',
            name='opis',
        ),
        migrations.AddField(
            model_name='samochod',
            name='numer_rejestracyjny',
            field=models.CharField(default='', max_length=7, verbose_name='Numer rejestracyjny'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='nazwa_serwisu',
            field=models.CharField(default='', max_length=256, verbose_name='Nazwa warsztatu/serwisu'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='notatki',
            field=models.CharField(default='', max_length=256, verbose_name='notatki'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='przebieg_wizyty',
            field=models.CharField(default='', max_length=256, verbose_name='przebieg_seriwsu'),
        ),
    ]
