# Generated by Django 6.0 on 2025-12-18 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numer rejestracyjny musi składać się z 2-10 dużych liter lub cyfr (bez spacji).', regex='^[A-Z0-9]{2,10}$')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Niepoprawny format VIN (17 znaków, wykluczając litery I, O, Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
