# Generated by Django 6.0 on 2025-12-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0002_alter_car_license_plate_alter_car_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workshop_name', models.CharField(max_length=255)),
                ('mileage', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment_custom_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='revise.car')),
            ],
        ),
    ]
