# Generated by Django 6.0 on 2025-12-19 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0003_appointment'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE revise_car ALTER COLUMN year TYPE integer USING EXTRACT(YEAR FROM year)::integer;',
            reverse_sql='ALTER TABLE revise_car ALTER COLUMN year TYPE date USING TO_DATE(year::text, \'YYYY\');'
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[
                django.core.validators.MinValueValidator(1900), 
                django.core.validators.MaxValueValidator(2025)
            ]),
        ),
    ]
