# Generated by Django 6.0 on 2025-12-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000000)]),
        ),
    ]
