# Generated by Django 6.0 on 2025-12-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarzadzaj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Koszt (PLN)')),
                ('opis', models.CharField(max_length=200, verbose_name='Opis usterki/przeglądu')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naprawy', to='zarzadzaj.samochod')),
            ],
        ),
    ]
